#本机的端口号
server:
  port: 8088

#数据库的密码
#数据库的用户名
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/foodie-shop-dev?useUnicode=true & characterEncoding=utf-8 &
      useSSL=true & serverTimezone=Asia/Shanghai
    username: root
    password: 114678
  # 连接池相关配置
  hikari:
   connection-timeout: 30000 # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQ
   minimum-idle: 5 # 最小连接数
   maximum-pool-size: 20 # 最大连接数
   auto-commit: true # 自动提交
   idle-timeout: 600000 # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
   pool-name: DateSourceHikariCP # 连接池名字
   max-lifetime: 1800000 # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟
   connection-test-query: SELECT 1


#这个是扫描到Entity实体包的路径，可根据自己的配置
mybatis:
  mapper-locations: classpath:/Mapper/*.xml
  type-aliases-package: com.acer.Entity

